version: '3'
services:
  web:
    image: nginx:1.25.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
  psql:
    image: postgres:15
    environment:
      POSTGRES_ROOT_PASSWORD: 'secret_root'
      POSTGRES_USER: 'tutorial_user'
      POSTGRES_PASSWORD: 'secret_tutorial'
      POSTGRES_DATABASE: 'tutorial_db'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata: {}